### ISSUE TITLE
Pixel installation

### ISSUE THREAD

**Issue by lgatto** [Candihub/pixel#302]
Following up from #301, this time with a fully working docker installation, I hit the following error:
```
$ git clone git@github.com:Candihub/pixel.git
Cloning into 'pixel'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 5393 (delta 0), reused 0 (delta 0), pack-reused 5392
Receiving objects: 100% (5393/5393), 7.30 MiB | 5.02 MiB/s, done.
Resolving deltas: 100% (3400/3400), done.
$  cd pixel
$ make bootstrap 
Building web
Step 1/23 : FROM python:3.6
 ---> 3e4c2972dc8d
Step 2/23 : ARG IS_NOT_PRODUCTION
 ---> Using cache
 ---> 9539178a780e
Step 3/23 : ARG BUILD_DATE
 ---> Using cache
 ---> 7e423485927d
Step 4/23 : ARG VCS_REF
 ---> Using cache
 ---> 8fc657926eda
Step 5/23 : ARG VERSION
 ---> Using cache
 ---> bea2ba9aac8d
Step 6/23 : LABEL org.label-schema.build-date=$BUILD_DATE       org.label-schema.name="Pixel"       org.label-schema.description="Integration of smart 'omics' data"       org.label-schema.url="https://pixel.candihub.eu/"       org.label-schema.vcs-ref=$VCS_REF       org.label-schema.vcs-url="https://github.com/Candihub/pixel/"       org.label-schema.vendor="CandiHub"       org.label-schema.version=$VERSION       org.label-schema.schema-version="1.0"
 ---> Using cache
 ---> fae18b1b17d5
Step 7/23 : RUN pip install pipenv --upgrade
 ---> Using cache
 ---> 90a02a898b46
Step 8/23 : RUN groupadd --gid 10001 app &&     useradd --uid 10001 --gid 10001 --home /app --create-home app
 ---> Using cache
 ---> 616252424d16
Step 9/23 : RUN su app -c "mkdir /app/pixel"
 ---> Using cache
 ---> 227de4354da9
Step 10/23 : WORKDIR /app/pixel
 ---> Using cache
 ---> 0f270e64ca6e
Step 11/23 : COPY Pipfile Pipfile
 ---> Using cache
 ---> 9a263e268996
Step 12/23 : COPY Pipfile.lock Pipfile.lock
 ---> Using cache
 ---> 2d959a3524fd
Step 13/23 : RUN su app -c "if [ -z $IS_NOT_PRODUCTION ]; then pipenv --bare install ; else pipenv --bare install -d ; fi" &&     rm -fr /app/.cache/pip
 ---> Using cache
 ---> b1531605b1b7
Step 14/23 : COPY . /app/pixel
 ---> Using cache
 ---> 627badab943f
Step 15/23 : RUN mkdir -p /usr/local/etc/gunicorn
 ---> Using cache
 ---> a9e7361068d6
Step 16/23 : COPY docker/usr/local/etc/gunicorn/pixel.py /usr/local/etc/gunicorn/pixel.py
 ---> Using cache
 ---> 9b0d947f44bf
Step 17/23 : RUN su app -c "mkdir run"
 ---> Using cache
 ---> b3bfa0f7455d
Step 18/23 : USER app
 ---> Using cache
 ---> 1bbd1a67767d
Step 19/23 : RUN mkdir -p public/media &&     mkdir -p public/static
 ---> Using cache
 ---> 36de9df8a33a
Step 20/23 : ENV DJANGO_SETTINGS_MODULE=pixel.settings     DJANGO_CONFIGURATION=Production     DJANGO_SECRET_KEY=ThisIsAFakeKeyUsedForBuildingPurpose
 ---> Using cache
 ---> dc53e07f7459
Step 21/23 : RUN pipenv run ./manage.py collectstatic -c
 ---> Using cache
 ---> 38b7a8df23a9
Step 22/23 : ENTRYPOINT ["pipenv", "run"]
 ---> Using cache
 ---> 4c151b4e3e4e
Step 23/23 : CMD ["gunicorn", "-c", "/usr/local/etc/gunicorn/pixel.py", "pixel.wsgi:application"]
 ---> Using cache
 ---> e33cc90735a2
Successfully built e33cc90735a2
Successfully tagged pixel-dev_web:latest
Waiting until database is up
make[1]: Entering directory '/home/lgatto/tmp/pixel'
Starting pixel-dev_db_1 ... done
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, data, sessions, submission, viewflow
Running migrations:
  No migrations to apply.
make[1]: Leaving directory '/home/lgatto/tmp/pixel'
Starting pixel-dev_db_1 ... done
Installed 6 object(s) from 1 fixture(s)
Starting pixel-dev_db_1 ... done
Installed 10 object(s) from 1 fixture(s)
Starting pixel-dev_db_1 ... done
Will generate 3 experiments and 10 pixel sets with 20 pixels each…
Traceback (most recent call last):
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
apps.core.models.DoesNotExist: Analysis matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/app/pixel/apps/core/management/commands/make_development_fixtures.py", line 103, in handle
    n_pixels_per_set=n_pixels_per_set
  File "/app/pixel/apps/core/management/commands/make_development_fixtures.py", line 33, in make_development_fixtures
    pixel_sets = factories.PixelSetFactory.create_batch(n_pixel_sets)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/base.py", line 575, in create_batch
    return [cls.create(**kwargs) for _ in range(size)]
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/base.py", line 575, in <listcomp>
    return [cls.create(**kwargs) for _ in range(size)]
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/base.py", line 563, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/base.py", line 500, in _generate
    return step.build()
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/builder.py", line 272, in build
    step.resolve(pre)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/builder.py", line 221, in resolve
    self.attributes[field_name] = getattr(self.stub, field_name)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/builder.py", line 375, in __getattr__
    extra=context,
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/declarations.py", line 324, in evaluate
    return self.generate(step, defaults)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/declarations.py", line 414, in generate
    return step.recurse(subfactory, params, force_sequence=force_sequence)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/builder.py", line 233, in recurse
    return builder.build(parent_step=self, force_sequence=force_sequence)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/builder.py", line 279, in build
    kwargs=kwargs,
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/base.py", line 314, in instantiate
    return self.factory._create(model, *args, **kwargs)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/django.py", line 163, in _create
    return cls._get_or_create(model_class, *args, **kwargs)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/factory/django.py", line 154, in _get_or_create
    instance, _created = manager.get_or_create(*args, **key_fields)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/tagulous/models/tagged.py", line 228, in get_or_create
    return super(TaggedQuerySet, self).get_or_create(**safe_fields)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/tagulous/models/tagged.py", line 209, in create
    obj = super(TaggedQuerySet, self).create(**safe_fields)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1111, in execute_sql
    for sql, params in self.as_sql():
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in as_sql
    for obj in self.query.objs
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1064, in <listcomp>
    for obj in self.query.objs
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1013, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/fields/files.py", line 296, in pre_save
    file.save(file.name, file.file, save=False)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/site-packages/django/core/files/storage.py", line 321, in _save
    os.makedirs(directory)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/app/.local/share/virtualenvs/pixel-0lGAHb0G/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app/pixel/public'
make: *** [Makefile:40: bootstrap] Error 1
```
The system is/has
```
$ uname -a
Linux 4.14.78-1-MANJARO #1 SMP PREEMPT Sun Oct 21 07:57:51 UTC 2018 x86_64 GNU/Linux
$ docker --version
Docker version 18.06.1-ce, build e68fc7a215
$ docker-compose --version 
docker-compose version 1.22.0, build unknown
$ python --version
Python 3.7.1
```
Thank you in advance.

**Comment by gaellelelandais** [comment]
@jmaupetit and @willdurand : can you help with this ? Many thanks !

**Comment by jmaupetit** [comment]
Hi @lgatto ! I can reproduce your issue. This is a permission issue that occurs in development: the docker user (uid: 10001) has no write permission on the app volume that belongs to the local user. I'll propose a PR to fix it.

**Comment by lgatto** [comment]
Thank you @jmaupetit. I'll wait for you PR.

**Comment by lgatto** [comment]
Thank you @willdurand - I haven't had time to test it locally but will do next week latest.
